esphome:
  name: esphome-wemos-d1-shielded
  friendly_name: esphome-wemos-d1-shielded

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rZ+RebKWolKnNKkDlGiG6UML+mTrUbOlW2LHVcbr0aw="

ota:
  - platform: esphome
    password: "782a374f26a67d090fc324e4f7680a77"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Wemos-D1-Shielded"
    password: "DwAHg18gEs19"

captive_portal:
    